/**
 * 初次加载时候的各个事件-init
 */

export const GETINFO_SUCCESS = 'GETINFO_SUCCESS'
export const GETSETTINGS_SUCCESS = 'GETSETTINGS_SUCCESS'
export const GETMYINFO_SUCCESS = 'GETMYINFO_SUCCESS'
export const GETMYINFO_FAILURE = 'GETMYINFO_FAILURE'
export const SETSIGN_SUCCESS = 'SETSIGN_SUCCESS'
export const SHOWTOOLTIP = 'SHOWTOOLTIP'
export const CLOSETOOLTIP = 'CLOSETOOLTIP'
export const GETWATCHHISTORY_SUCCESS = 'GETWATCHHISTORY_SUCCESS'
export const WATCH_VIDEO = 'WATCH_VIDEO'
export const FETCHNAVNUM_SUCCESS = 'FETCHNAVNUM_SUCCESS'
export const FETCHNAVNUM_FAILURE = 'FETCHNAVNUM_FAILURE'
export const UPADTE_USER_STATE = 'UPADTE_USER_STATE'
export const GETUPSTAT_SUCCESS = 'GETUPSTAT_SUCCESS'
export const UPDATE_WATCHLATER = 'UPDATE_WATCHLATER'

/**
 * 主题，头图
 */
export const FETCHTOPPHOTO_SUCCESS = 'FETCHTOPPHOTO_SUCCESS'
export const FETCHSKIN_SUCCESS = 'FETCHSKIN_SUCCESS'
export const UPLOADTOUTU_SUCCESS = 'UPLOADTOUTU_SUCCESS'
export const GETBCOIN_SUCCESS = 'GETBCOIN_SUCCESS'

/**
 * 置顶视频
 */
export const GETTOPVIDEOS_SUCCESS = 'GETTOPVIDEO_SUCCESS'
export const GETMASTERPIECE_SUCCESS = 'GETMASTERPIECE_SUCCESS'
export const GETTOPVIDEOS_FAILURE = 'GETTOPVIDEO_FAILURE'
export const GETMASTERPIECE_FAILURE = 'GETMASTERPIECE_FAILURE'
export const SETTOPVIDEOS_SUCCESS = 'SETTOPVIDEO_SUCCESS'
export const SETMASTERPIECE_SUCCESS = 'SETMASTERPIECE_SUCCESS'
export const DELETEMASTERPIECE_SUCCESS = 'DELETEMASTERPIECE_SUCCESS'
export const DELETETOPVIDEOS_SUCCESS = 'DELETETOPVIDEOS_SUCCESS'
export const CLEARSELECTVIDEOS = 'CLEARSELECTVIDEOS'

/**
 * 投稿视频
 */
export const FETCHSUBMITVIDEOS_START = 'FETCHSUBMITVIDEOS_START'
export const GETSUBMITVIDEOS_SUCCESS = 'GETSUBMITVIDEOS_SUCCESS'
export const GETSUBMITVIDEOS_FAILURE = 'GETSUBMITVIDEOS_FAILURE'

/**
 * 频道
 */
export const GETCHANNEL_SUCCESS = 'GETCHANNEL_SUCCESS'
export const GETCHANNELWITHARCHIVES_SUCCESS = 'GETCHANNELWITHARCHIVES_SUCCESS'
export const GETCHANNELINFO_SUCCESS = 'GETCHANNELINFO_SUCCESS'

/**
 * 收藏夹
 */
export const GETFAV_START = 'GETFAV_START'
export const GETFAV_SUCCESS = 'GETFAV_SUCCESS'
export const GETFAV_FAILURE = 'GETFAV_FAILURE'
export const FETCHFAVDETAIL_START = 'FETCHFAVDETAIL_START'
export const FETCHFAVDETAIL_SUCCESS = 'FETCHFAVDETAIL_SUCCESS'
export const FETCHFAVDETAIL_FAILURE = 'FETCHFAVDETAIL_FAILURE'
export const COPYVIDEO_SUCCESS = 'COPYVIDEO_SUCCESS'
export const DELFAVLIST_SUCCESS = 'DELFAVLIST_SUCCESS'
export const SETFAVLIST_SUCCESS = 'SETFAVLIST_SUCCESS'
export const RENAMEFAV_SUCCESS = 'RENAMEFAV_SUCCESS'
export const GETMYFAV_START = 'GETMYFAV_START'
export const GETMYFAV_SUCCESS = 'GETMYFAV_SUCCESS'
export const GETMYFAV_FAILURE = 'GETMYFAV_FAILURE'
export const GETTOPICS_START = 'GETTOPICS_START'
export const GETTOPICS_SUCCESS = 'GETTOPICS_SUCCESS'
export const GETTOPICS_FAILURE = 'GETTOPICS_FAILURE'
export const DELTOPICS_SUCCESS = 'DELTOPICS_SUCCESS'
export const ARTICLES_SUCCESS = 'ARTICLES_SUCCESS'
export const GETALLARTICLE_START = 'GETALLARTICLE_START'
export const GETALLARTICLE_SUCCESS = 'GETALLARTICLE_SUCCESS'
export const GETALLARTICLE_FAILURE = 'GETALLARTICLE_FAILURE'
export const DELINVALIDVIDEO_START = 'DELINVALIDVIDEO_START'
export const DELINVALIDVIDEO_SUCCESS = 'DELINVALIDVIDEO_SUCCESS'
export const DELINVALIDVIDEO_FAILURE = 'DELINVALIDVIDEO_FAILURE'
export const GETFAVPLAYLIST_START = 'GETFAVPLAYLIST_START'
export const GETFAVPLAYLIST_SUCCESS = 'GETFAVPLAYLIST_SUCCESS'
export const GETFAVPLAYLIST_FAILURE = 'GETFAVPLAYLIST_FAILURE'
export const GETFAVNAV_START = 'GETFAVNAV_START'
export const GETFAVNAV_SUCCESS = 'GETFAVNAV_SUCCESS'
export const GETFAVNAV_FAILURE = 'GETFAVNAV_FAILURE'
export const SETALBUMNAV_SUCCESS = 'SETALBUMNAV_SUCCESS'
export const SETFAVBANGUMINUM_SUCCESS = 'SETFAVBANGUMINUM_SUCCESS'
export const FETCHFAVTLIST_SUCCESS = 'FETCHFAVTLIST_SUCCESS'
export const FETCHFAVTLIST_FAILURE = 'FETCHFAVTLIST_FAILURE'
export const FETCHCREATEDLIST_START = 'FETCH_CREATEDLIST_START'
export const FETCHCREATEDLIST_SUCCESS = 'FETCH_CREATEDLIST_SUCCESS'
export const FETCHCREATEDLIST_FAILURE = 'FETCH_CREATEDLIST_FAILURE'
export const FETCHMYCREATEDLIST_SUCCESS = 'FETCH_MYCREATEDLIST_SUCCESS'
export const FETCHCOLLECTEDLIST_SUCCESS = 'FETCH_COLLECTEDLIST_SUCCESS'
export const FETCHFAVDETAILS_START = 'FETCHFAVDETAILS_START'
export const FETCHFAVDETAILS_SUCCESS = 'FETCHFAVDETAILS_SUCCESS'
export const FETCHFAVDETAILS_FAILURE = 'FETCHFAVDETAILS_FAILURE'
export const DELFAVPLAYLIST_SUCCESS = 'DELFAVPLAYLIST_SUCCESS'
export const THUMBUPORDOWN_SUCCESS = 'THUMBUPORDOWN_SUCCESS'
export const COLLFAVADD_SUCCESS = 'COLLFAVADD_SUCCESS'
export const COLLFAVDEL_SUCCESS = 'COLLFAVDEL_SUCCESS'
export const MOREVIDEO_SUCCESS = 'MOREVIDEO_SUCCESS'
export const DELFAVVIDEO_SUCCESS = 'DELFAVVIDEO_SUCCESS'
export const SHOWFAVSHARE_SUCCESS = 'SHOWFAVSHARE_SUCCESS'
export const MYCOLLFAVDEL_SUCCESS = 'MYCOLLFAVDEL_SUCCESS'
export const DELVIDEO_SUCCESS = 'DELVIDEO_SUCCESS'
export const SHAREPLAYLIST_SUCCESS = 'SHAREPLAYLIST_SUCCESS'
export const MODALADDFAV_LOAD = 'MODALADDFAV_LOAD'
export const MODALADDFAV_SUCCESS = 'MODALADDFAV_SUCCESS'
export const GETALBUMCOUNT_SUCCESS = 'GETALBUMCOUNT_SUCCESS' 
export const GETALBUMLIST_SUCCESS = 'GETALBUMLIST_SUCCESS' 
export const GETALBUMLIST_FAILURE = 'GETALBUMLIST_FAILURE' 
/**
 * 播单
 */
export const GETPLAYLIST_START = 'GETPLAYLIST_START'
export const GETPLAYLIST_SUCCESS = 'GETPLAYLIST_SUCCESS'
export const GETPLAYLIST_FAILURE = 'GETPLAYLIST_FAILURE'
export const GETPLAYLISTINFO_START = 'GETPLAYLISTINFO_START'
export const GETPLAYLISTINFO_SUCCESS = 'GETPLAYLISTINFO_SUCCESS'
export const GETPLAYLISTINFO_FAILURE = 'GETPLAYLISTINFO_FAILURE'
export const GETPLAYLISTAUTH = 'GETPLAYLISTAUTH'

/**
 * 首页交互
 */
export const TOGGLESPACESTATE = 'TOGGLESPACESTATE'

/**
 * 获取粉丝列表
 */
export const GETRELATIONLIST_SUCCESS = 'GETRELATIONLIST_SUCCESS'
export const GETRELATIONLIST_START = 'GETRELATIONLIST_START'
export const GETMANYINFOS_SUCCESS = 'GETMANYINFOS_SUCCESS'
export const GETFANSTAGS_SUCCESS = 'GETFANSTAGS_SUCCESS'
export const GETRELATIONLIST_FAILURE = 'GETRELATIONLIST_FAILURE'
export const GETFANSTAGS_FAILURE = 'GETFANSTAGS_FAILURE'
export const MOVEFROMBAN_SUCCESS = 'MOVEFROMBAN_SUCCESS'
export const REMOVEATTENTION_SUCCESS = 'REMOVEATTENTION_SUCCESS'
export const ADDATTENTION_SUCCESS = 'ADDATTENTION_SUCCESS'
export const REMOVELIST_SUCCESS = 'REMOVELIST_SUCCESS'
export const ADDATTENTION = 'ADDATTENTION'
export const REMOVEATTENTION = 'REMOVEATTENTION'
export const REMOVEFANS = 'REMOVEFANS'

/**
 * 用户空间设置
 */
export const SETINDEXORDER_SUCCESS = 'SETINDEXORDER_SUCCESS'
export const GETPERSONALTAGS_SUCCESS = 'GETPERSONALTAGS_SUCCESS'
export const GETPERSONALTAGS_FAILURE = 'GETPERSONALTAGS_FAILURE'
export const SETPERSONALTAGS_SUCCESS = 'SETPERSONALTAGS_SUCCESS'
export const SETPRIVACY_SUCCESS = 'SETPRIVACY_SUCCESS'

/**
 * 用户关系
 */
export const FETCH_NUMBERS_SUCCESS = 'FETCH_NUMBERS_SUCCESS'
export const UPDATE_RELATION = 'UPDATE_RELATION'
export const RELATION_WITH_UPER = 'RELATION_WITH_UPER'
export const GETKNIGHT_SUCCESS = 'GETKNIGHT_SUCCESS'
export const GETKNIGHT_START = 'GETKNIGHT_START'
export const DELCHANNEL_SUCCESS = 'DELCHANNEL_SUCCESS'
export const GETUSERTAG_START = 'GETUSERTAG_START'
export const GETUSERTAG_SUCCESS = 'GETUSERTAG_SUCCESS'
export const GETUSERTAG_FAILURE = 'GETUSERTAG_FAILURE'
export const GETUSERTAGS_START = 'GETUSERTAGS_START'
export const GETUSERTAGS_SUCCESS = 'GETUSERTAGS_SUCCESS'
export const GETUSERTAGS_FAILURE = 'GETUSERTAGS_FAILURE'
export const GET_ACCRELATION_SUCCESS = 'GET_ACCRELATION_SUCCESS'

/**
 * 付费课程
 */
export const GETPUGV_START = 'GETPUGV_START'
export const GETPUGV_SUCCESS = 'GETPUGV_SUCCESS'
export const GETPUGV_FAILURE = 'GETPUGV_FAILURE'
export const GETPUGVLIST_START = 'GETPUGVLIST_START'
export const GETPUGVLIST_SUCCESS = 'GETPUGVLIST_SUCCESS'
export const GETPUGVLIST_FAILURE = 'GETPUGVLIST_FAILURE'
export const UPDATEPUGVNUM_SUCCESS = 'UPDATEPUGVNUM_SUCCESS'
