export const relations = state => state.relations
export const attribute = state => state.attribute
export const relationList = state => state.relationList
export const knightsList = state => state.knightsList
export const knightsCount = state => state.knightsCount
export const isRelationListLoad = state => state.isRelationListLoad
export const getFansTags = state => state.tags
export const userTag = state => state.userTag
export const userTagList = state => state.userTagList
export const defaultGroupCount = state => state.defaultGroupCount
export const accRelation = state => state.accRelation
