export const favList = state => state.favList
export const isFavListLoad = state => state.isFavListLoad
export const myFavList = state => state.myFavList
export const isMyFavListLoad = state => state.isMyFavListLoad
export const favDetail = state => state.favDetail
export const isFavDetailLoad = state => state.isFavDetailLoad
export const topics = state => state.topics
export const favArticles = state => state.articles
export const isArticleListLoad = state => state.isArticleListLoad
export const isTopicLoad = state => state.isTopicLoad
export const idPlaylistListLoad = state => state.idPlaylistListLoad
export const delInvalidVideoStateNum = state => state.delInvalidVideoStateNum
export const playlists = state => state.playlists
export const favNavList = state => state.favNavList
export const isFarNavListLoad = state => state.isFarNavListLoad
export const tlist = state => state.tlist
export const createdList = state => state.createdList
export const collectedList = state => state.collectedList
export const favListDetails = state => state.favListDetails
export const isShowFavShare = state => state.isShowFavShare
export const isCreatedFavLoad = state => state.isCreatedFavLoad
export const myCreatedList = state => state.myCreatedList
export const isAddFavLoad = state => state.isAddFavLoad
export const modalAddFavList = state => state.modalAddFavList
